C	PROGRAM CADIN   (CMENDOZA.APR98/modified from CADCOM.F)
C       OPTION 1: MAKES INPUT FILE FOR CADILLAC NAMED CADIN.DAT
C		ALSO, MAKES WEIGHT.DAT & ARSZCAD.DAT FILES AND CAN
C		CREATE INLONG.DAT/INSHORT.DAT FILES PLUS FILE OF
C		SHEAR RIGIDITIES (RIGID.DAT) NEEDED BY PLISA.
C	OPTION 2: MAKE SUBFAULT LISTING USING COARSE GRID POINTS
C		(RATHER THAN FINE) FOR USE IN DWFE OR FAKEOUT RUNS.
C
      CHARACTER*4 EPI,MODL
      CHARACTER*32 FNAME
      REAL WGHT(500),TDP(50),BDP(50),TOPL(50),RGD(50)
      INTEGER ZERO,ONE
C
	ONE=1
	ZERO=0
      OPEN(UNIT=1,FILE='cadin.dat',STATUS='UNKNOWN',
     + ACCESS='SEQUENTIAL',FORM='FORMATTED')
	WRITE(6,*)' ENTER OUTPUT OPTION:'
	WRITE(6,*)' 1 = MAKE INPUT FILE FOR CADILLAC'
	WRITE(6,*)' 2 = MAKE A SUBFAULT LISTING USING COARSE'
	WRITE(6,*)'     GRID POINTS FOR DWFE'
	READ (5,*)NFLG
	IF (NFLG .NE. 1) GO TO 1000
      OPEN(UNIT=2,FILE='WEIGHT.DAT',STATUS='UNKNOWN',
     + ACCESS='SEQUENTIAL',FORM='FORMATTED')
	ISAVEH=0
	ITIMEH=0
	ITFEX=0
	WRITE(6,*)' DIGITAL GSN SYNTHETICS (1=YES, 0=NO)?'
	WRITE(6,*)' IF NO, INPUT IS FOR WWSSN SYNTHETICS.'
	READ (5,*) IGDSN
	WRITE(6,*)' LONG-PERIOD (1) OR SHORT-PERIOD RESPONSE (2)?'
	READ (5,*) INSTRH
	WRITE(1,*) ISAVEH,INSTRH,ITIMEH,IGDSN,ITFEX
	WRITE(1,*) ONE
C
C        Q OPERATOR
C
      WRITE(6,*)' ENTER 0 ... FOR CONSTANT T STAR MODEL'
      WRITE(6,*)' ENTER 1 ... FOR MINSTER ATTENUATION OPERATOR'
      WRITE(6,*)' ENTER 2 ... FOR CHOY ATTENUATION OPERATOR'
      READ (5,*)IATTEN
      WRITE(1,*) IATTEN
      IF (IATTEN .EQ. 0) THEN
      WRITE(6,*)' ENTER THE VALUE OF T STAR (T/Q)'
      READ(5,*) TQ
      WRITE(1,*) TQ
      ENDIF
      IF (IATTEN .EQ. 1) THEN
      WRITE(6,*)' ENTER VALUES OF T STAR, TAUBM, TAULM, TRAVEL TIME.'
      WRITE(6,*)' ENTER ZERO FOR DEFAULT VALUES OF 1.,1000.,.01,600.'
      READ(5,*) TQ,TAUBM,TAULM,TAU
      WRITE (1,*) TQ,TAUBM,TAULM,TAU
      ENDIF
      IF (IATTEN .EQ. 2) THEN
      WRITE(6,*)' THIS OPTION WILL REQUIRE SEPARATE FILE FROM CHOY'
      WRITE(6,*)' ENTER 1 FOR LOW ATTENUATION OPERATOR'
      WRITE(6,*)' ENTER 2 FOR HIGH ATTENUATION OPERATOR'
      READ(5,*) ICHOY
      WRITE(1,*) ICHOY
      ENDIF
      WRITE(6,*)' NCOMP  =1, VERTICAL, =2, RADIAL, =3, TRANSVERSE'
      WRITE(6,*)' MODE  =1, P-WAVE, =2, SV-WAVE, =3, SH-WAVE'
      WRITE(6,*)' ENTER NCOMP & MODE'
      READ(5,*) NCOMP,MODE
      WRITE(1,*) NCOMP,MODE
C
C        READ IN FAULT-PLANE PARAMETERS
C        READ IN SOURCE TIME FUNCTION
C
      WRITE(1,*) ONE
      WRITE(6,*)' ENTER EVENT & MODEL [A4,1X,A4]'
      READ(5,500)  EPI,MODL
      WRITE(1,500) MODL,EPI
  500 FORMAT( A4, 1X, A4 )
      WRITE(1,*) ONE
      WRITE(6,*)' THE DIP CANT BE NEGATIVE BUT MAY BE GREATER THAN 90'
      WRITE(6,*)' IF DIP>90, THEN RAKE=+90 IS STILL THRUST FAULT'
      WRITE(6,*)' ENTER STRIKE, DIP, & RAKE'
      READ(5,*) STRK,DIP,RAKE
      WRITE(1,*) STRK,DIP,RAKE
      WRITE(1,*) ONE
      WRITE(6,*)' ENTER MOMENT DESIRED (dyne-cm)'
      READ(5,*) FMNT
      WRITE(1,*) FMNT/(10.**26)
      WRITE(1,*) ONE
      WRITE(6,*)'  IS THE HYPOCENTER ON THE FAULT (1=YES;0=NO)?'
      READ(5,*) JFLG
      IF (JFLG .EQ. 0) THEN
	WRITE(6,*)'  ENTER TLAG,XC,YC'
	READ(5,*) TLAG,XC,YC
  	WRITE(1,*) TLAG,XC,YC
	ENDIF
      IF (JFLG .EQ. 1) WRITE(1,*) '  0.  0.  0.'
      WRITE(1,*) ONE
      WRITE(6,*)'  SELECT TIME FUNCTION:'
      WRITE(6,*)'  TRAPEZOID =1, DIGITIZED TIME FUNCTION =2'
      READ(5,*) ICIP
      WRITE(1,*) ICIP
      IF (ICIP .EQ. 2) GO TO 510
      WRITE(6,*)'  ENTER DT1, DT2, & DT3'
      READ(5,*)DT1,DT2,DT3
      WRITE(1,*)DT1,DT2,DT3
      GO TO 520
  510 CONTINUE
      WRITE(6,*)' ENTER TIME FUNCTION FILE NAME'
      READ(5,*) FNAME
      WRITE(1,'(A32)') FNAME
  520 CONTINUE
      WRITE(1,*) ONE
C
C     INPUT FAULT PARAMETERS
C
      WRITE(6,*)' ENTER FAULT LENGTH (KM)'
      READ(5,*)FLEN
1000  WRITE(6,*)' HOW MANY SUBFAULTS ALONG STRIKE & DOWN-DIP'
      READ(5,*)NSTR,NDIP
      IF (NFLG .NE. 1) THEN
	ISTR=0
	GO TO 2000
	ENDIF
      DO 550 I=1,NDIP+1
	DO 525 J=1,NSTR+1
 525	WGHT(J)=FLOAT(ONE)
 550  WRITE(2,'(30F3.0)')(WGHT(J),J=1,NSTR+1)
      CLOSE(2)
      WRITE(6,*)' HOW MANY INTERMEDIATE PT. SOURCES ALONG STRIKE'
      WRITE(6,*)' AND DOWN-DIP PER SUBFAULT'
      READ(5,*)ISTR,IDIP
2000  WRITE(6,*)' ENTER TOP & BOTTOM DEPTHS OF FAULT'
      READ(5,*)TDEP,BDEP
      IF (NFLG .NE. 1) GO TO 3000
      WRITE(6,*)' ENTER HYPOCENTER DEPTH & DIST FROM LEFT EDGE OF FAULT'
      READ(5,*)HDEP,XDIST
      WRITE(6,*)' ENTER RUPTURE VELOCITY (KM/SEC)'
      READ(5,*)RVEL
      WRITE(1,*)FLEN
      WRITE(1,*)NSTR+1
      WRITE(1,*)ISTR
      WRITE(1,*)TDEP,BDEP
      WRITE(1,*)NDIP+1
      WRITE(1,*)IDIP
      WRITE(1,*)HDEP
      WRITE(1,*)XDIST
      WRITE(1,*)RVEL
      WRITE(1,*)NSTR*NDIP
C
C     COMPUTE & OUTPUT SUBFAULT INDICES & DEPTHS
C
3000  DINT=((BDEP-TDEP)/NDIP)
      NDX1=1
      DO 2 I=1,NSTR
	D1=TDEP
	DO 1 J=1,NDIP
		NDX2=NDX1+ISTR+1
		WRITE(1,*)NDX1,NDX2
		D2=D1+DINT
		WRITE(1,*)D1,D2
		IF (I.EQ.1) THEN
			TDP(J)=D1
			BDP(J)=D2
			ENDIF
		D1=D2
1		CONTINUE
	NDX1=NDX2
2     CONTINUE
      WRITE(1,*)' 0'
      CLOSE(1)
C
C     MAKE PARAMETER FILE FOR CADILLAC
C
      OPEN(UNIT=3,FILE='ARSZCAD.DAT',STATUS='UNKNOWN',
     + ACCESS='SEQUENTIAL',FORM='FORMATTED')
      IF (NFLG.NE.1) STOP
      II=((ISTR+1)*NSTR)+20
      JJ=((IDIP+1)*NDIP)+20
      WRITE(3,10)NSTR*NDIP+100
      WRITE(3,20)II,JJ,NSTR+1,NDIP+1
  10  FORMAT(6X,'PARAMETER(MRAY=250,MLEG=50,NSTN=50,MSUB=',I3,
     +',MLAY=10,MSOR=1,')
  20  FORMAT(5X,'+MTX=',I3,',MTY=',I3,',MX=',I2,',MY=',I2,')')
      CLOSE(3)
C
C     MAKE INLONG.DAT/INSHORT.DAT FILE
C
      WRITE(6,*)' DO YOU WANT TO MAKE INLONG.DAT/INSHORT.DAT'
      WRITE(6,*)' and RIGID.DAT FILES (1=YES, 0=NO)?'
      READ (5,*) IFLG
      IF (IFLG .EQ. 0) GO TO 400
      WRITE(6,*)' ENTER STATION LIST FILE'
      READ (5,'(A32)') FNAME
      OPEN(UNIT=3,FILE=FNAME,STATUS='UNKNOWN',
     + ACCESS='SEQUENTIAL',FORM='FORMATTED')
      FNAME = 'INLONG.DAT'
      DT = 0.1
      SCALE = 0.7874
      NP = 1024
      NPL = 10
      IF (INSTRH .EQ. 2) THEN
	FNAME = 'INSHORT.DAT'
	DT = 0.01
	SCALE = 0.2362
	ENDIF
      OPEN(UNIT=4,FILE=FNAME,STATUS='UNKNOWN',
     + ACCESS='SEQUENTIAL',FORM='FORMATTED')
      WRITE(4,25) DT,NP,NPL,SCALE,FLOAT(ONE),ZERO,ZERO,ZERO
      WRITE(6,*)' ENTER NUM/STATIONS IN STATION LIST'
      READ(5,*) NS
      WRITE(4,'(8X,I2)') NS
      DO 100 I=1,NS
      READ(3,30) STNM,DEL,AZ,RP,PVEL,SVEL
 100  WRITE(4,30) STNM,DEL,AZ,RP,PVEL,SVEL
      WRITE(6,*)' ENTER NUM/LAYERS IN CRUSTAL MODEL, incl HALFSPACE'
      READ(5,*) NLS
      WRITE(4,'(I10)')NLS+1
      HVAL = .001
      WRITE(4,35)HVAL,HVAL,HVAL,FLOAT(ZERO)
      TOPL(1)=0.
      DO 200 I=1,NLS
      WRITE(6,*)' ENTER PV, SV, DENSITY, AND THICKNESS FOR LAYER:',I
      READ(5,*) HPV,HSV,HDN,HKM
      WRITE(4,35)HPV,HSV,HDN,HKM
      TOPL(I+1)=HKM+TOPL(I)
      RGD(I)=HDN*(HSV**2)/10.
C     WRITE(6,*)' TOP,BTM DEPTHS, RIGIDITY:',TOPL(I),TOPL(I+1),RGD(I)
 200  CONTINUE
  25  FORMAT(F5.3,2I5,2F10.4,3I5)
  30  FORMAT(A4,6X,5F10.3)
  35  FORMAT(3(F5.3,5X),F5.2)
      CLOSE(3)
      CLOSE(4)
C
C     MAKE RIGID.DAT FILE
C
      OPEN(UNIT=7,FILE='RIGID.DAT',STATUS='UNKNOWN',
     + ACCESS='SEQUENTIAL',FORM='FORMATTED')
      do 300 n=1,ndip
	d1=tdp(n)
	d2=bdp(n)
C	write(6,*)n,d1,d2
	do 250 i=1,nls
	   if (d1.ge.topl(i).and.d1.lt.topl(i+1)) then
		write(7,*) d1,d2,rgd(i)
		go to 300
		endif
 250	continue
 300	continue
 400	continue
      close(7)

      STOP
      END
