C                PROGRAM CONCAT2
C
C
C     THIS VERSION OF CONCAT JOINS BINARY SYNTHETICS OR DATA FILES CREATED
C     WITH CADILLAC, SEISRESP, OR TELMOD.  UP TO THREE FILES ARE CONCATENATED.
C     THE RESULTING NUMBER OF RECORDS IS WRITTEN OUT AT THE HEAD OF THE
C     BINARY OUTPUT FILE.
C
      DIMENSION NST(3),TEL(16000)
      CHARACTER*40 IFG1,IFG2,IFG3,IFG4
      WRITE(6,*)' ENTER FILE TYPE (1=DATA, 2=SYNTHETICS)'
      READ(5,*) NTYPE
      WRITE(6,600)
 600  FORMAT(1X,'HOW MANY FILES DO YOU WISH TO CONCATENATE',/,
     +1X,'MAXIMUM OF THREE')
      READ(5,*) NCAT
      WRITE(6,601)
 601  FORMAT(1X,'ENTER FILE NAMES IN THE ORDER YOU WISH',/,
     +1X,'THEM TO BE ADDED')
      READ(5,602) IFG1
 602  FORMAT(A)
      OPEN(UNIT=1,FILE=IFG1,STATUS='OLD',ACCESS='SEQUENTIAL',
     +FORM='UNFORMATTED')
      READ(5,602) IFG2
      OPEN(UNIT=2,FILE=IFG2,STATUS='OLD',ACCESS='SEQUENTIAL',
     +FORM='UNFORMATTED')
      IF(NCAT .EQ. 2) GO TO 2
      READ(5,602) IFG3
      OPEN(UNIT=3,FILE=IFG3,STATUS='OLD',ACCESS='SEQUENTIAL',
     +FORM='UNFORMATTED')
   2  WRITE(6,603)   
 603  FORMAT(1X,'ENTER BINARY OUTPUT FILE NAME')
      READ(5,602) IFG4
      OPEN(UNIT=10,FILE=IFG4,STATUS='NEW',ACCESS='SEQUENTIAL',
     +FORM='UNFORMATTED')
      NSUBF=1
      IF (NTYPE .EQ. 1) GO TO 100
      WRITE(6,604)
 604  FORMAT(1X,'HOW MANY SUBFAULTS ARE THERE')
      READ(5,*) NSUBF
 100  READ(1) NSTA1
      READ(2) NSTA2
      IF(NCAT .EQ. 2) GO TO 3
      READ(3) NSTA3
   3  IF(NCAT .EQ. 2) NSTA=NSTA1+NSTA2
      IF(NCAT .EQ. 3) NSTA=NSTA1+NSTA2+NSTA3
      NST(1)=NSTA1
      NST(2)=NSTA2
      NST(3)=NSTA3
      WRITE(10) NSTA
      DO 20 NC=1,NCAT
      NS=NST(NC)
      IUN=NC
      DO 10 LOOP=1,NS
      DO 30 NSB=1,NSUBF
      IF (NTYPE .EQ. 1) READ(IUN) NT,DT
      IF (NTYPE .EQ. 2) READ(IUN) NT,DT,TSTART
      READ(IUN) (TEL(IP),IP=1,NT)
      IF (NTYPE .EQ. 1) WRITE(10) NT,DT
      IF (NTYPE .EQ. 2) WRITE(10) NT,DT,TSTART
      WRITE(10) (TEL(IP),IP=1,NT)
  30  CONTINUE
  10  CONTINUE
  20  CONTINUE
 200  CLOSE(1)
      CLOSE(2)
      IF(NCAT .EQ. 3) CLOSE(3)
      CLOSE(10)
      STOP
      END
